<?php

namespace AppBundle\Repository;

/**
 * RangListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangListRepository extends \Doctrine\ORM\EntityRepository
{
}
